config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/m-team-kit/mlflow-auth-gui:
      branch: main
      repo: https://github.com/m-team-kit/mlflow-auth-gui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-khaki-toad.sh
        container: qc.acc_cranky-aqua-turkey
  QC.Doc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-vermilion-opossum.sh
        container: qc.doc_lovely-burgundy-heron
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-cerise-dachshund.sh
        container: qc.doc_scummy-taupe-indri
  QC.Lic:
    repos:
      github.com/m-team-kit/mlflow-auth-gui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-crimson-anteater.sh
        container: qc.lic_zippy-chocolate-chicken
  QC.Ver:
    repos:
      github.com/m-team-kit/mlflow-auth-gui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-gamboge-goose.sh
        container: qc.ver_whiny-heliotrope-maltese
timeout: 5400
