config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/m-team-kit/mlflow-auth-gui:
      branch: main
      repo: https://github.com/m-team-kit/mlflow-auth-gui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-indigo-numbat.sh
        container: qc.acc_cranky-persimmon-clam
  QC.Doc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-cardinal-uakari.sh
        container: qc.doc_shabby-plum-lobster
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-amethyst-tarsier.sh
        container: qc.doc_snoopy-cinnabar-chinook
      github.com/m-team-kit/mlflow-auth-gui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-heliotrope-eleuth.sh
        container: qc.doc_flimsy-linen-dodo
  QC.Lic:
    repos:
      github.com/m-team-kit/mlflow-auth-gui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-orchid-mandrill.sh
        container: qc.lic_snappy-brown-sloth
  QC.Met:
    repos:
      github.com/m-team-kit/mlflow-auth-gui cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-alizarin-gar.sh
        container: qc.met_frumpy-silver-olm
      github.com/m-team-kit/mlflow-auth-gui validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-khaki-jellyfish.sh
        container: qc.met_flaky-myrtle-fly
  QC.Sty:
    repos:
      github.com/m-team-kit/mlflow-auth-gui hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-lilac-barnacle.sh
        container: qc.sty_hazy-teal-uakari
      github.com/m-team-kit/mlflow-auth-gui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-teal-malamute.sh
        container: qc.sty_slaphappy-carmine-bongo
  QC.Ver:
    repos:
      github.com/m-team-kit/mlflow-auth-gui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-burgundy-foxhound.sh
        container: qc.ver_scaly-peach-dingo
timeout: 5400
