config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/m-team-kit/mlflow-auth-gui:
      branch: main
      repo: https://github.com/m-team-kit/mlflow-auth-gui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cyan-lionfish.sh
        container: qc.acc_pretty-aqua-coati
  QC.Doc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-lavender-binturong.sh
        container: qc.doc_wheezy-lemon-akbash
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-sangria-rattlesnake.sh
        container: qc.doc_scaly-amber-hyena
  QC.Lic:
    repos:
      github.com/m-team-kit/mlflow-auth-gui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-peach-hound.sh
        container: qc.lic_muzzy-harlequin-greyhound
  QC.Ver:
    repos:
      github.com/m-team-kit/mlflow-auth-gui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-saffron-forest.sh
        container: qc.ver_goopy-smalt-dormouse
timeout: 5400
