config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-docs:
      branch: master
      repo: https://github.com/ai4os/ai4-docs
    github.com/m-team-kit/mlflow-auth-gui:
      branch: main
      repo: https://github.com/m-team-kit/mlflow-auth-gui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-lilac-molly.sh
        container: qc.acc_scummy-cinnabar-alligator
  QC.Doc:
    repos:
      github.com/ai4os/ai4-docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-carmine-seal.sh
        container: qc.doc_slimy-chocolate-oyster
      github.com/ai4os/ai4-docs git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-zucchini-indri.sh
        container: qc.doc_tasty-zucchini-leopard
      github.com/ai4os/ai4-docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-lemon-ibis.sh
        container: qc.doc_lovely-pink-ray
      github.com/ai4os/ai4-docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-fuchsia-balinese.sh
        container: qc.doc_sickly-goldenrod-swan
  QC.Lic:
    repos:
      github.com/m-team-kit/mlflow-auth-gui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-teal-retriever.sh
        container: qc.lic_wiggy-silver-fossa
  QC.Met:
    repos:
      github.com/m-team-kit/mlflow-auth-gui cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-russet-bird.sh
        container: qc.met_shaggy-white-fousek
      github.com/m-team-kit/mlflow-auth-gui validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-burgundy-iguana.sh
        container: qc.met_beady-aqua-meerkat
  QC.Sty:
    repos:
      github.com/m-team-kit/mlflow-auth-gui hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-sapphire-fowl.sh
        container: qc.sty_ready-bronze-mandrill
      github.com/m-team-kit/mlflow-auth-gui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-chestnut-sparrow.sh
        container: qc.sty_droopy-teal-tarsier
  QC.Ver:
    repos:
      github.com/m-team-kit/mlflow-auth-gui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-harlequin-abyssinian.sh
        container: qc.ver_slaphappy-green-spider
timeout: 5400
