config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/m-team-kit/mlflow-auth-gui:
      branch: main
      repo: https://github.com/m-team-kit/mlflow-auth-gui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-puce-grouse.sh
        container: qc.acc_breezy-chartreuse-macaque
  QC.Doc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-malachite-buffalo.sh
        container: qc.doc_queasy-maroon-ant
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-amethyst-woodlouse.sh
        container: qc.doc_nippy-mustard-dhole
      github.com/m-team-kit/mlflow-auth-gui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-gamboge-camel.sh
        container: qc.doc_woolly-asparagus-opossum
  QC.Lic:
    repos:
      github.com/m-team-kit/mlflow-auth-gui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-fuchsia-rabbit.sh
        container: qc.lic_scaly-zucchini-argentino
  QC.Met:
    repos:
      github.com/m-team-kit/mlflow-auth-gui cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-persimmon-swan.sh
        container: qc.met_ugly-seashell-centipede
      github.com/m-team-kit/mlflow-auth-gui validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.surly-burgundy-sloth.sh
        container: qc.met_pokey-pink-llama
  QC.Sty:
    repos:
      github.com/m-team-kit/mlflow-auth-gui hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-maroon-dunker.sh
        container: qc.sty_cloudy-lime-crane
      github.com/m-team-kit/mlflow-auth-gui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-chartreuse-fowl.sh
        container: qc.sty_wiggy-teal-chameleon
  QC.Ver:
    repos:
      github.com/m-team-kit/mlflow-auth-gui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-aquamarine-anteater.sh
        container: qc.ver_wimpy-sapphire-chamois
timeout: 5400
