config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-docs:
      branch: master
      repo: https://github.com/ai4os/ai4-docs
    github.com/m-team-kit/mlflow-auth-gui:
      branch: main
      repo: https://github.com/m-team-kit/mlflow-auth-gui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-maroon-molly.sh
        container: qc.acc_gummy-yellow-axolotl
  QC.Doc:
    repos:
      github.com/ai4os/ai4-docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-black-kudu.sh
        container: qc.doc_sunny-cinnamon-sheepdog
      github.com/ai4os/ai4-docs git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-gold-setter.sh
        container: qc.doc_chummy-cobalt-alligator
      github.com/ai4os/ai4-docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-viridian-crane.sh
        container: qc.doc_breezy-persimmon-monster
      github.com/ai4os/ai4-docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-turquoise-blue.sh
        container: qc.doc_skinny-orange-slug
  QC.Lic:
    repos:
      github.com/m-team-kit/mlflow-auth-gui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-orchid-reindeer.sh
        container: qc.lic_homey-brass-mau
  QC.Met:
    repos:
      github.com/m-team-kit/mlflow-auth-gui cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-pear-gibbon.sh
        container: qc.met_sloppy-cornflower-stoat
      github.com/m-team-kit/mlflow-auth-gui validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.homey-sangria-deer.sh
        container: qc.met_sleepy-magenta-ladybird
  QC.Sty:
    repos:
      github.com/m-team-kit/mlflow-auth-gui hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-maroon-chow.sh
        container: qc.sty_whiny-tomato-caracal
      github.com/m-team-kit/mlflow-auth-gui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-bistre-pinscher.sh
        container: qc.sty_leaky-orchid-bracke
  QC.Ver:
    repos:
      github.com/m-team-kit/mlflow-auth-gui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-burgundy-lynx.sh
        container: qc.ver_flimsy-peach-cow
timeout: 5400
