config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui:
      branch: main
      repo: https://codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-malachite-magpie.sh
        container: qc.acc_snippy-aquamarine-spaniel
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-smalt-mandrill.sh
        container: qc.doc_crappy-turquoise-dunker
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-ecru-cockroach.sh
        container: qc.doc_shabby-gamboge-akita
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-denim-crab.sh
        container: qc.doc_wiggy-auburn-lemur
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cornflower-toucan.sh
        container: qc.lic_dorky-aquamarine-hyena
  QC.Met:
    repos:
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-alizarin-frigatebird.sh
        container: qc.met_hazy-tan-gopher
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-saffron-woodlouse.sh
        container: qc.met_muzzy-asparagus-snake
  QC.Sty:
    repos:
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cornflower-starfish.sh
        container: qc.sty_flaky-platinum-dollar
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-tan-tang.sh
        container: qc.sty_clammy-peach-raccoon
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-harlequin-squirrel.sh
        container: qc.ver_trippy-cobalt-toucan
timeout: 5400
