config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/m-team-kit/mlflow-auth-gui:
      branch: main
      repo: https://github.com/m-team-kit/mlflow-auth-gui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-chocolate-bordeaux.sh
        container: qc.acc_nerdy-grey-seahorse
  QC.Doc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-corn-setter.sh
        container: qc.doc_chewy-dandelion-markhor
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-indigo-robin.sh
        container: qc.doc_snazzy-firebrick-hornet
  QC.Lic:
    repos:
      github.com/m-team-kit/mlflow-auth-gui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-brown-sloth.sh
        container: qc.lic_foggy-cobalt-mau
  QC.Ver:
    repos:
      github.com/m-team-kit/mlflow-auth-gui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-salmon-quokka.sh
        container: qc.ver_fuzzy-jade-chamois
timeout: 5400
